# Use a base image with Python and G++ (for C++ compilation)
FROM python:3.9-slim

# Install G++ for C++ compilation
RUN apt-get update && apt-get install -y g++

# Install dependencies for FastAPI
RUN pip install fastapi uvicorn python-multipart


# Set working directory
WORKDIR /app

# Copy the FastAPI app code into the container
COPY . /app

# Expose the port that FastAPI will run on
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]