# Use an openjdk base image for Java
FROM openjdk:11-jdk-slim
# Install dependencies for FastAPI and Python
RUN apt-get update && apt-get install -y python3-pip

# Install FastAPI and Uvicorn
RUN pip3 install fastapi uvicorn python-multipart


# Set working directory
WORKDIR /app

# Copy the FastAPI app code into the container
COPY . /app

# Expose the port that FastAPI will run on
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]